// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package com.team3546.season2014.RoboBuilt.subsystems;
import com.team3546.season2014.RoboBuilt.RobotMap;
import com.team3546.season2014.RoboBuilt.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 * Contains the 4 drive motors and a doubleSolenoid for a two speed shifter
 * Currently set up for tank drive
 * The shifter is initialized to retracted, or high gear
 */
public class DriveTrain extends Subsystem {

    public static final DoubleSolenoid.Value highGear = DoubleSolenoid.Value.kReverse;
    public static final DoubleSolenoid.Value lowGear = DoubleSolenoid.Value.kForward;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController frontLeft = RobotMap.driveTrainFrontLeft;
    SpeedController frontRight = RobotMap.driveTrainFrontRight;
    SpeedController backLeft = RobotMap.driveTrainBackLeft;
    SpeedController backRight = RobotMap.driveTrainBackRight;
    RobotDrive robotDrive4 = RobotMap.driveTrainRobotDrive4;
    DoubleSolenoid shifterSolenoid = RobotMap.driveTrainShifterSolenoid;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new JoystickTankDrive());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        //Initialize to high gear
        shifterSolenoid.set(highGear);
    }
    public void takeJoystickInputs(Joystick left, Joystick right) {
        robotDrive4.tankDrive(left, right);
    }
    public void stop() {
        robotDrive4.drive(0,0);
    }
    /**
     * Shifts gears to the specified level
     * @param setPoint level
     */
    public void shift(DoubleSolenoid.Value setPoint) {
        shifterSolenoid.set(setPoint);
    }
}
