// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package com.team3546.season2014.RoboBuilt.subsystems;
import com.team3546.season2014.RoboBuilt.Robot;
import com.team3546.season2014.RoboBuilt.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 * Contains a doubleSolenoid to control the position of the arms, and a speed controller for the arm motors
 * Initializes the arms to retracted
 * Initializes the motor to off
 */
public class PickupArm extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DoubleSolenoid armMovementSolenoid = RobotMap.pickupArmArmMovementSolenoid;
    SpeedController pickupArmMotor = RobotMap.pickupArmPickupArmMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        //Initialize the arms to retracted
        armMovementSolenoid.set(DoubleSolenoid.Value.kReverse);
        pickupArmMotor.set(0);
    }
    /**
     * Set the position of the arms
     * @param position position
     */
    public void setArmMovementSolenoid(DoubleSolenoid.Value position) {
        armMovementSolenoid.set(position);
    }
    /**
     * Sets the state of the pickup motor
     * @param setPoint "Off", "In", or "Out"
     */
    public void setPickupArmMotor(String setPoint) {
        if (setPoint.equals("Off")) {
            pickupArmMotor.set(0);
        } else if (setPoint.equals("In")) {
            pickupArmMotor.set(Robot.pickupArmMotorSpeed);
        } else if (setPoint.equals("Out")) {
            pickupArmMotor.set(-Robot.pickupArmMotorSpeed);
        }
    }
}
